"""
UmaEdge — Hybrid Ensemble & Divergence Detector.

Implements the two-model (fundamental + odds-aware) ensemble strategy
and the DivergenceDetector that identifies high-alpha bet signals when
the model probability diverges significantly from the market-implied
probability.

Sprint 2.2 — Hybrid Ensemble with Adaptive Blending.
Priority 1-3 — Longshot bias fixes, adaptive blending, and bet sizing.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

import numpy as np

log = logging.getLogger("ensemble")


# ---------------------------------------------------------------------------
# Alpha Signal dataclass
# ---------------------------------------------------------------------------

@dataclass
class AlphaSignal:
    """
    A bet signal generated by the DivergenceDetector.

    Represents a situation where the fundamental model probability
    diverges from the market-implied probability by more than the
    minimum threshold — indicating potential edge.
    """
    entry_id: int
    fundamental_prob: float    # Model probability without odds features
    market_prob: float          # 1 / market_odds (implied probability)
    odds_aware_prob: float      # Model probability with odds features
    divergence: float           # fundamental_prob - market_prob
    alpha_score: float          # Risk-adjusted alpha (divergence penalised for longshots)


# ---------------------------------------------------------------------------
# Divergence Detector
# ---------------------------------------------------------------------------

class DivergenceDetector:
    """
    Detects bet signals by comparing fundamental model probabilities
    to market-implied probabilities.

    A signal is generated when:
        fundamental_prob - market_implied_prob >= min_divergence

    Signals are sorted by alpha_score (descending) so the highest-edge
    bets appear first.

    Alpha score = divergence * longshot_penalty
    where longshot_penalty = 1 / sqrt(market_odds / 5.0)
    to penalise high-odds signals that are structurally noisy.
    """

    def __init__(self, min_divergence: float = 0.05):
        """
        Args:
            min_divergence: Minimum required divergence (fundamental - market)
                to generate an AlphaSignal. Default: 5%.
        """
        self.min_divergence = min_divergence

    def detect(
        self,
        entry_ids: np.ndarray,
        fundamental_probs: np.ndarray,
        odds_aware_probs: np.ndarray,
        market_odds: np.ndarray,
    ) -> list:
        """
        Detect high-alpha signals across a field.

        Args:
            entry_ids: Entry IDs (shape: [n]).
            fundamental_probs: Model win probabilities without odds features (shape: [n]).
            odds_aware_probs: Model win probabilities with odds features (shape: [n]).
            market_odds: Market payout odds (e.g. 5.0 = 5-to-1). (shape: [n])

        Returns:
            List of AlphaSignal sorted by alpha_score descending.
        """
        signals = []

        for i in range(len(entry_ids)):
            odds = float(market_odds[i])

            # Skip invalid odds
            if odds is None or not np.isfinite(odds) or odds <= 0:
                continue

            market_prob = 1.0 / odds
            divergence = float(fundamental_probs[i]) - market_prob

            if divergence < self.min_divergence:
                continue

            # Longshot alpha penalty: higher odds -> noisier signal
            # Penalty = 1 / sqrt(odds / 5.0) -- at odds=5, penalty=1.0 (no change)
            # At odds=20, penalty=0.5; at odds=80, penalty=0.25
            longshot_penalty = 1.0 / np.sqrt(max(odds, 1.0) / 5.0)
            alpha_score = divergence * longshot_penalty

            signals.append(
                AlphaSignal(
                    entry_id=int(entry_ids[i]),
                    fundamental_prob=float(fundamental_probs[i]),
                    market_prob=float(market_prob),
                    odds_aware_prob=float(odds_aware_probs[i]),
                    divergence=float(divergence),
                    alpha_score=float(alpha_score),
                )
            )

        # Sort by alpha_score descending
        signals.sort(key=lambda s: s.alpha_score, reverse=True)
        return signals


# ---------------------------------------------------------------------------
# Hybrid Ensemble
# ---------------------------------------------------------------------------

class HybridEnsemble:
    """
    Blends a fundamental model (no odds features) with an odds-aware model.

    The blend weight is adaptive: for short-priced horses where the market
    signal is most reliable, the odds-aware model weight increases. For
    longshots where market inefficiency is more common, the fundamental
    model weight increases.

    Adaptive weight = fundamental weight (w_fund)
    Combined prob = w_fund * fundamental_prob + (1 - w_fund) * odds_aware_prob

    w_fund range: [0.2, 0.6]
    - At low odds (e.g. 2.0): w_fund = 0.6 (fundamental model dominant)
    - At high odds (e.g. 100+): w_fund = 0.2 (odds-aware model dominant)
    """

    def __init__(
        self,
        w_fund_low: float = 0.6,    # Fundamental weight at low odds
        w_fund_high: float = 0.2,   # Fundamental weight at high odds
        odds_breakpoint: float = 20.0,  # Sigmoid midpoint (odds at w=0.4)
        steepness: float = 0.05,    # How quickly weight transitions
    ):
        self.w_fund_low = w_fund_low
        self.w_fund_high = w_fund_high
        self.odds_breakpoint = odds_breakpoint
        self.steepness = steepness

    def _compute_adaptive_weights(self, odds: np.ndarray) -> np.ndarray:
        """
        Compute fundamental model weight for each horse based on market odds.

        Uses a sigmoid decay from w_fund_low (at low odds) to w_fund_high
        (at high odds), centred at odds_breakpoint.

        Args:
            odds: Market payout odds, shape [n].

        Returns:
            Fundamental model weights in [w_fund_high, w_fund_low], shape [n].
        """
        odds = np.asarray(odds, dtype=float)
        # Sigmoid: as odds increase, t goes from 0 -> 1
        t = 1.0 / (1.0 + np.exp(-self.steepness * (odds - self.odds_breakpoint)))
        # Interpolate: low odds -> w_fund_low; high odds -> w_fund_high
        weights = self.w_fund_low - t * (self.w_fund_low - self.w_fund_high)
        return weights

    def blend(
        self,
        fundamental_probs: np.ndarray,
        odds_aware_probs: np.ndarray,
        market_odds: np.ndarray,
    ) -> np.ndarray:
        """
        Blend fundamental and odds-aware probabilities using adaptive weights.

        Args:
            fundamental_probs: Probabilities from odds-free model. Shape [n].
            odds_aware_probs: Probabilities from odds-aware model. Shape [n].
            market_odds: Market payout odds. Shape [n].

        Returns:
            Combined probabilities. Shape [n].
        """
        w_fund = self._compute_adaptive_weights(market_odds)
        combined = w_fund * fundamental_probs + (1.0 - w_fund) * odds_aware_probs

        # Normalise to sum to 1 over the field if more than one horse
        if len(combined) > 1:
            total = combined.sum()
            if total > 0:
                combined = combined / total

        return combined
